.github/workflows/bazel_lint.yml
.github/workflows/cpp_lint.yml
.github/workflows/cpplint.yml

Enable C++, Starlark language linting in pushes and pull requests

---

.github/PULL_REQUEST_TEMPLATE.md

Replace PR_TEMPLATE with a more descriptive one.
The new template comes from Envoy github
**Testing:**
CI testing and local testing.
**Docs Changes:**
PULL_REQUEST_TEMPLATE
**[Optional Fixes #Issue]**

Replace PR_TEMPLATE with a more descriptive one

---

.github/workflows/bazel_test.yml

Test an example _run targets in CI
Test an example empty_fuzz_test_run targets with a short timeout (eg 5 seconds) in CI
**Testing:**
CI testing and local testing.
**Fixes #36**
modified:   .github/workflows/bazel_test.yml

Test an example _run targets in CI

---

fuzzing/common.bzl

Explicitly create directory in fuzzing_corpus
**Testing:**
modified:   fuzzing/common.bzl

Explicitly create directory in fuzzing_corpus

---

fuzzing/common.bzl

Rule fuzzing_dictionary()
Invokes fuzzing/tools:validate_dict to validate and merge dictionaries
**Testing:**
**Fixes #16**
modified:   fuzzing/common.bzl

Rule fuzzing_dictionary()

---

README.md

Updates the snippet importing bazel-rules-fuzzing to the latest commit
**Testing:** N/A
**Docs Changes:**
README.md

Updates the snippet importing bazel-rules-fuzzing to the latest commit

---

.gitignore

**Testing:**
**Docs Changes:**
**[Optional Fixes #Issue]**

Define .gitignore file excluding Bazel generated files.

---

.bazelrc
.github/workflows/bazel_lint.yml
.github/workflows/bazel_test.yml
.github/workflows/cpp_lint.yml
BUILD
CODEOWNERS
WORKSPACE
examples/empty_fuzz_test.cc
examples/fuzzed_data_provider_fuzz_test.cc
examples/hang_fuzz_test.cc
examples/msan_fuzz_test.cc
examples/oom_fuzz_test.cc
fuzzing/BUILD
fuzzing/cc_deps.bzl
fuzzing/common.bzl
fuzzing/dependency_imports.bzl
fuzzing/repositories.bzl
fuzzing/tools/BUILD
fuzzing/tools/dict_validation.py
fuzzing/tools/dict_validation_test.py
fuzzing/tools/launcher.py
fuzzing/tools/make_corpus_dir.py
fuzzing/tools/validate_dict.py

**Testing:**
**Docs Changes:**
**[Optional Fixes #Issue]**

Formatting nit: Remove empty comment lines.

---

.bazelrc
.github/workflows/bazel_test.yml
README.md
fuzzing/cc_deps.bzl
fuzzing/engines/BUILD
fuzzing/engines/libfuzzer_launcher.sh
fuzzing/engines/libfuzzer_stub.cc
fuzzing/private/BUILD
fuzzing/private/common.bzl
fuzzing/private/engine.bzl
fuzzing/private/engine_test.bzl
fuzzing/private/fuzz_test.bzl
fuzzing/private/util.bzl
fuzzing/repositories.bzl
fuzzing/tools/launcher.py

Define new cc_fuzzing_engine rule.

---

CODEOWNERS

This way, they will be able to approve PRs.

Add the repository collaborators as CODEOWNERS

---

.github/PULL_REQUEST_TEMPLATE.md

I'm currently working on the project primarily from VSCode, which automatically populates PRs from commit descriptions.

Remove the PR template. 

---

.bazelrc
README.md
WORKSPACE
examples/BUILD
examples/input_buffer_overflow_fuzz_test.cc
examples/new_buffer_overflow_fuzz_test.cc
fuzzing/dependency_imports.bzl
fuzzing/engines/BUILD
fuzzing/engines/honggfuzz_launcher.sh
fuzzing/repositories.bzl
honggfuzz.BUILD

Add Honggfuzz engine support through the --config=asan-honggfuzz build config.

---

.bazelrc
README.md
WORKSPACE
docs/BUILD
docs/cc-fuzzing-rules.md
examples/BUILD
examples/input_buffer_overflow_fuzz_test.cc
examples/new_buffer_overflow_fuzz_test.cc
fuzzing/cc_deps.bzl
fuzzing/dependency_imports.bzl
fuzzing/engines/BUILD
fuzzing/engines/honggfuzz_launcher.sh
fuzzing/private/BUILD
fuzzing/repositories.bzl
honggfuzz.BUILD
update_docs.sh

This documentation will be referenced in the README file, once it is cleaned up and revamped.

Auto-generate documentation for all fuzzing rules.

---

.bazelrc
.github/workflows/bazel_test.yml
fuzzing/BUILD
fuzzing/engines/BUILD
fuzzing/engines/replay_launcher.sh

Also make this engine the default //fuzzing:cc_engine value, and update our regression tests to run on {replay,libfuzzer,honggfuzz} configurations.

Add the replay engine as a new cc_fuzzing engine.

---

.bazelrc
.github/workflows/bazel_test.yml

Reviewers: This is the same as PR #112 which was accidentally merged into #111 and then erased in a forced push.

Pin the compiler version used in this workspace and for CI workflows.

---

docs/BUILD
fuzzing/private/fuzz_test.bzl

Fix macro parameter naming according to conventions. Also fix a minor typo.

Convention fix

---

fuzzing/private/oss_fuzz/repository.bzl

Force the linking of the UBSAN runtime in OSS-Fuzz builds.

---

fuzzing/private/java_utils.bzl

This commit removes the following two types of runfiles declared by the
java_binary target passed into the jazzer_fuzz_binary rule which are not
used during the execution of the Jazzer target:
* the local JDK files in @local_jdk (Jazzer launches the JVM directly)
* the individual jars on the runtime classpath (Jazzer executes the
deploy jar, which contains the contents of all these jars).

Remove unused jazzer_fuzz_binary runfile

---

fuzzing/private/oss_fuzz/package.bzl

This deviates from the usual Bazel runfiles layout, but is required
since ClusterFuzz executes fuzz targets in subdirectories and would thus
duplicate every C++ fuzz target.

Do not link to binary from its own runfiles tree

---

README.md

@fmeum PTAL. This is in connection to #190

Updated the README file to clarify prerequisites.

---

.bcr/metadata.template.json
.bcr/presubmit.yml

Taken from edits made to https://github.com/bazelbuild/bazel-central-registry/pull/5240

Sync back BCR config
