bazel-contrib/rules_fuzzing

examples/BUILD
=> suppress "uninitialized" warning for msan_fuzz_test

WORKSPACE, fuzzing/tools/BUILD, fuzzing/tools/launcher.py
Fixes #17 
This script aims at providing an uniform command line interface behind a number of arbitrary fuzzing engines. For now the script perform a plain fuzzing run with a given timeout.  
The command to use this script looks like
```
bazel run --config=asan-libfuzzer //examples:empty_fuzz_test --run_under='//fuzzing/tools:launcher --timeout=5'
```
=> Initial version of the Python launcher script for invoking fuzz target executables

fuzzing/tools/launcher.py
Add -max_total_time argument into launcher.py
The launcher script only pass -timeout, which set a timer for a single
fuzzing test loop, but that doesn't work for the overall fuzzing test.
Add -max_total_time to fix this problem.
The discussion about this problem can found in https://github.com/googleinterns/bazel-rules-fuzzing/pull/34#issuecomment-658982939
**Testing:**
CI testing and local testing.
modified:   fuzzing/tools/launcher.py
=> Add -max_total_time argument into launcher.py

fuzzing/cc_deps.bzl
Forward all attributes that `cc_fuzz_test` can't handle to `cc_test` by
using keyword arguments `**kwargs`.
Since `cc_test` doesn't accept `corpus` but we may pass `corpus` in `cc_fuzz_test`, we need to delete `corpus` entry in `**kwargs` after calling `launcher_corpus` in #38 
**Testing:**
**Fixes #26**
modified:   fuzzing/cc_deps.bzl
=> Use **kwargs to forward attributes in cc_fuzz_test

WORKSPACE, fuzzing/cc_deps.bzl, fuzzing/common.bzl
Rule fuzzing_corpus for collecting corpus files
Example usage:
fuzzing_corpus(
name = "my_fuzzer_corpus",
srcs = [
"file1.txt",
"path/to/file2.txt",
],
)
**Testing:**
**Fixes #12**
modified:   fuzzing/cc_deps.bzl
modified:   fuzzing/common.bzl
=> Rule fuzzing_corpus for collecting corpus files

examples/BUILD, examples/dict_dir/invalid.dict, examples/dict_dir/valid.dict, fuzzing/cc_deps.bzl, fuzzing/common.bzl, fuzzing/tools/launcher.py
1) Adds --dict to launcher.py
2) Adds fuzzing_dictionary as an implicit argument to fuzzing_launcher
3) Adds dict_dir directory with valid and invalid dictionaries
4) Adds empty_fuzz_test_with_dict and empty_fuzz_test_with_invalid_dict
The second issue described in #43 is not clear to me yet, waiting to fix.
**Testing:**
**Fixes #43**
modified:   examples/BUILD
new file:   examples/dict_dir/invalid.dict
new file:   examples/dict_dir/valid.dict
modified:   fuzzing/cc_deps.bzl
modified:   fuzzing/common.bzl
modified:   fuzzing/tools/launcher.py
=> Adds dictionary support to launcher

fuzzing/cc_deps.bzl, fuzzing/common.bzl, fuzzing/tools/launcher.py
Deletes is_regression parameter in fuzzing_launcher.
After deleting this parameter, the user can't set the launcher for regression test directly, instead the user can set it in the command or a shell script.
This change comes from the discussion in https://github.com/envoyproxy/envoy/pull/12530#discussion_r476725983
**Testing:**
Local testing and CI testing.
=> Deletes is_regression parameter in fuzzing_launcher

fuzzing/tools/launcher.py
The launcher script wraps the original fuzzing binary, to let user pass
the optional arguments to the fuzzing binary, a list argument
optional_args is added to the launcher.py.
**Testing:**
Local testing and CI testing.
modified:   fuzzing/tools/launcher.py
=> Adds optional_args to launcher.py

examples/buffer_overflow_fuzz_test.cc
In the current implementation, the compiler optimizes away the no-op
path when built in the 'opt' configuration.
=> Fix the buffer overflow example in opt build mode.

.bazelrc
Following @robertswiecki's feedback in #75.
=> Explicitly disable libfuzzer instrumentation in Honggfuzz.

README.md, WORKSPACE, examples/BUILD, examples/re2_fuzz_test.cc, fuzzing/dependency_imports.bzl, fuzzing/repositories.bzl, fuzzing/requirements.txt
To do so, this change bumps up the python_rules dependency, which simplifies the import of PIP rules. It also adds a new RE2 example, which showcases a "real" API and demonstrates the fuzz test's ability to discover new coverage.
=> Revamp the README documentation of the rules.

README.md, fuzzing/private/fuzz_test.bzl
This ensures that the label is resolved correctly regardless of the place the macro is instantiated.
=> Use the workspace name for labels in macros.

README.md
The commit ID is past the fix to the issue that prevented the rules from being imported in another workspace.
=> Update the repo HTTP archive source location in the README example.

README.md, docs/cc-fuzzing-rules.md, fuzzing/private/fuzz_test.bzl
~I was not yet able to regenerate the Markdown documentation due to #83.~
PR #85 should fix #83 and I was now able to re-generate the documentation in this PR.
=> Expand the documentation of the cc_fuzz_test macro.

.bazelrc, .github/workflows/bazel_test.yml, README.md, docs/BUILD, docs/cc-fuzzing-rules.md, fuzzing/BUILD, fuzzing/instrum_opts.bzl, fuzzing/private/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/private/instrument.bzl
This approach eliminates the need for inlining the instrumentation options in the bazelrc file and simplifies the adoption of the rules.
=> Reimplement fuzzing instrumentation using Bazel transitions.

fuzzing/engines/BUILD, fuzzing/engines/libfuzzer_stub.cc, fuzzing/instrum_opts.bzl
Without this change, any other binary that may be built on the transitive dependency chain will also get linked with libFuzzer, resulting in a linker error (duplicate main functions).
=> Move the libfuzzer linkopts to the stub cc_library, such that only the top-level fuzz test is instrumented.

.bazelrc, README.md, fuzzing/BUILD, fuzzing/engines/BUILD, fuzzing/engines/libfuzzer_stub.cc, fuzzing/instrum_opts.bzl, fuzzing/private/instrument.bzl
* The build flags need to be referenced with the absolute workspace name, so the names resolve correctly when imported in a different repo.
* The fuzzing build mode is now optional so it can be disabled in the projects that wish so.
=> Fix a number of instrumentation issues that occur when other projects use the fuzzing rules.

fuzzing/instrum_opts.bzl, fuzzing/private/instrument.bzl
These are needed to support importing CFLAGS and CXXFLAGS from the environment, as a prerequisite for adding OSS-Fuzz support.
=> Add support for C-only and C++-only instrumentation options.

docs/BUILD, docs/cc-fuzzing-rules.md, fuzzing/dependency_imports.bzl, fuzzing/private/fuzz_test.bzl, fuzzing/repositories.bzl
The rule is currently unused and will be superseded by other rules creating their own corpus ZIP archive.
=> Remove the <name>_corpus_zip rule and its deps.

fuzzing/engines/BUILD, fuzzing/private/common.bzl, fuzzing/private/engine.bzl, fuzzing/private/engine_test.bzl
The goal is to establish more clearly the relationship between the launcher script, its runfiles, and the environment variables available.
=> Refactor the cc_fuzzing_engine implementation to use more precise naming.

.bazelrc, docs/BUILD, examples/BUILD, fuzzing/BUILD, fuzzing/instrum_opts.bzl, fuzzing/private/fuzz_test.bzl, fuzzing/private/oss_fuzz/BUILD, fuzzing/private/oss_fuzz/BUILD.tpl, fuzzing/private/oss_fuzz/instrum.bzl.tpl, fuzzing/private/oss_fuzz/package.bzl, fuzzing/private/oss_fuzz/repository.bzl, fuzzing/repositories.bzl
The support includes (a) a repository rule that extracts OSS-Fuzz environment information and makes it available hermetically in a `@rules_fuzzing_oss_fuzz` repo, and (b) a new target in the `cc_fuzz_test` macro that packages a fuzz test and its dependencies in the OSS-Fuzz format.
=> Add OSS-Fuzz support to the Bazel fuzzing rules.

fuzzing/private/fuzz_test.bzl, fuzzing/tools/make_corpus_dir.py
This prevents a Bazel glitch in which the corpus directory is absent from the fuzz target runfiles if the directory is empty. It also simplifies the downstream logic handling the corpus directory.
=> Make the corpus directory always contain files, even if just an empty file.

fuzzing/engines/honggfuzz_launcher.sh, fuzzing/engines/libfuzzer_launcher.sh
This is a prerequisite for adding "regression unit test" support.
=> Implement the regression mode flag in the libFuzzer and Honggfuzz launchers.

.github/workflows/bazel_test.yml, docs/BUILD, docs/cc-fuzzing-rules.md, examples/BUILD, fuzzing/private/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/private/regression.bzl
This is a specialization of the launcher rule, defined as a test. The cc_fuzz_test macro is also refactored such that the test rule runs by default when invoking "bazel test".
=> Add a test rule for running a fuzz test against the seed corpus.

docs/cc-fuzzing-rules.md, fuzzing/cc_deps.bzl, fuzzing/private/fuzz_test.bzl
The macro can be instantiated in custom definitions of the cc_fuzz_test macro.
=> Separate the set of associated targets in a cc_fuzz_test rule in a distinct macro.

fuzzing/private/fuzz_test.bzl, fuzzing/private/oss_fuzz/package.bzl
For a `cc_fuzz_test(name = <name>)` target, the base name used in the OSS-Fuzz package should be `<name>`, rather than the internal name of the instrumented binary.
Tested this is working correctly:
```
$ bazel build //examples:re2_fuzz_test_oss_fuzz
INFO: Analyzed target //examples:re2_fuzz_test_oss_fuzz (1 packages loaded, 52 targets configured).
INFO: Found 1 target...
Target //examples:re2_fuzz_test_oss_fuzz up-to-date:
bazel-bin/examples/re2_fuzz_test_oss_fuzz.tar
INFO: Elapsed time: 2.222s, Critical Path: 1.45s
INFO: 30 processes: 4 internal, 26 linux-sandbox.
INFO: Build completed successfully, 30 total actions
$ tar -tvf bazel-bin/examples/re2_fuzz_test_oss_fuzz.tar
drwxr-xr-x sbucur/primarygroup 0 2021-01-25 22:21 ./
-rw-r--r-- sbucur/primarygroup 170 2021-01-25 22:21 …
```
=> Fix the base name of the OSS-Fuzz targets.

fuzzing/private/oss_fuzz/repository.bzl
These variables are less likely to be subject to clobbering during builds.
@inferno-chromium @oliverchang If you'd like to make these available by default in the OSS-Fuzz environment, please let me know if you'd like to use different variable names here.
=> Allow picking the OSS-Fuzz instrumentation flags from $FUZZING_CFLAGS/$FUZZING_CXXFLAGS, too.

WORKSPACE, fuzzing/requirements.txt
This helps the fuzzing rules be consistent with Envoy's dependency policies (envoyproxy/envoy#14834).
=> Pin the hashes of all Python requirements.

fuzzing/private/oss_fuzz/package.bzl
This is in connection to https://github.com/google/oss-fuzz/issues/5317
=> Make sure the staging dir in OSS-Fuzz packaging rule is cleaned up, to permit non-sandboxed runs.

fuzzing/replay/BUILD, fuzzing/replay/replay_main.cc, fuzzing/replay/status_util.cc, honggfuzz.BUILD
* more portable strerror_r handling (borrowed from abseil)
* adjust honggfuzz build options
* notify linker about weak ref in :replay_main
See https://github.com/bazelbuild/rules_fuzzing/issues/138
=> Fix OSX build

examples/dictionaries/valid_part1.dict, fuzzing/tools/dict_validation.py, fuzzing/tools/dict_validation_test.py, fuzzing/tools/validate_dict.py
Refactor dict validation using regular expression for simplification and improvement.
After the change, the validation will:
- Disallow `"\"`, `""`, and any non-space suffix after the entry ends (e.g. `"entry"suffix`).
- Disallow unesacped '"' in enties. Raw '"' can indeed be used in libFuzzer due to implementation details,
but it is undocumented (https://llvm.org/docs/LibFuzzer.html#dictionaries), implementation-dependent, and confusing.
- Show file paths and line numbers with errors.
Fixes #47
=> Improve dict validation

fuzzing/private/binary.bzl, fuzzing/private/common.bzl, fuzzing/private/engine.bzl, fuzzing/private/engine_test.bzl, fuzzing/private/oss_fuzz/package.bzl, fuzzing/private/regression.bzl
By removing the engine_library_info field of CcFuzzingEngineInfo and relying exlusively on the DefaultInfo and language-specific *Info providers to propagate the information about the engine library, CcFuzzingEngineInfo can become almost completely generic in the language.
This PR performs the required refactoring and renames the provider to FuzzingEngineInfo. It also drops the Cc prefix of CcFuzzingBinaryInfo, which no longer depends on the language.
=> Decompose FuzzingEngineInfo into orthogonal providers

README.md, docs/BUILD, docs/java-fuzzing-rules.md, examples/java/com/example/JavaFuzzTest.java, examples/java/com/example/JavaNativeFuzzTest.cpp, fuzzing/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/repositories.bzl, update_docs.sh
This updates Jazzer and adds Java documentation to the README and Stardoc.
@stefanbucur I have some ideas on how to implement oss-fuzz support, but I don't think this is critical for the next release - most OSS Java projects don't use Bazel.
=> Prepare Java release

examples/fuzzed_data_provider_fuzz_test.cc
This works around the CI failures observed in #146 through #149, but does not make any attempts to address the unknown root cause.
=> Manually include <limits> to fix CI failures

docs/BUILD, examples/BUILD, examples/runfiles_fuzz_test.cc, fuzzing/private/BUILD, fuzzing/private/oss_fuzz/package.bzl, fuzzing/private/util.bzl
The runfiles tree of a fuzzing_binary is now packaged correctly for
OSS-Fuzz.
For a fuzz test foo in workspace bar, the runfiles are resolved relative
to the foo.runfiles/bar directory in the output .tar. A wrapper script
ensures that the real fuzz test binary is called with the correct
working directory.
The workspace_name of the binary label attribute in fuzzing_binary is
needed in the construction of the binary's runfiles tree and thus added
to the FuzzingBinaryInfo provider.
Closes #100.
=> Add full runfiles tree support

fuzzing/private/oss_fuzz/BUILD.tpl, fuzzing/private/oss_fuzz/repository.bzl
OSS-Fuzz provides certain files for use by all fuzz targets depending on the language declared in the project.yaml, e.g. the Jazzer driver and agent. These files should be used instead of building them themselves, primarily because this allows seemless updates to the fuzzing engines without requiring the project to update to a new version of rules_fuzzing.
This commit introduces a list of runfiles (identified by workspace name and short_path) that should be replaced with the OSS-Fuzz provided files. This is achieved by replacing the actual runfile in the generated tar archive with a relative symlink pointing to the corresponding file with the same basename in the top-level $OUT directory.
This resolves 1. in https://github.com/bazelbuild/rules_fuzzing/pull/146#discussion_r632299433 in a …
=> Use OSS-Fuzz provided top-level files

fuzzing/private/oss_fuzz/repository.bzl
Since https://github.com/google/oss-fuzz/commit/73d78b88790b501f119801c4f68463180b76e1d9, OSS-Fuzz now provides the Jazzer driver with the correct sanitizer in jazzer_driver_with_sanitizer. This simplifies the logic in `repository.bzl`.
=> Account for new OSS-Fuzz Jazzer binary names

fuzzing/engines/honggfuzz_launcher.sh, fuzzing/engines/jazzer_launcher.sh, fuzzing/engines/libfuzzer_launcher.sh
For LibFuzzer, do not read the output corpus in regression mode.
For Honggfuzz, use dry-run-only mode instead of minimize mode for more expected behavior, and enable outputs from the target for easier debugging.
=> Various tweaks in engine launchers for regression mode.

.github/workflows/oss_fuzz.yml, README.md, docs/java-fuzzing-rules.md, examples/java/BUILD, examples/java/com/example/JavaNativeRunfileFuzzTest.cpp, examples/java/com/example/JavaNativeRunfileFuzzTest.h, examples/java/com/example/JavaNativeRunfileFuzzTest.java, fuzzing/private/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/private/java_utils.bzl, fuzzing/private/local_jazzer_sanitizer_options.sh, fuzzing/private/oss_fuzz_jazzer_sanitizer_options.sh, fuzzing/repositories.bzl
This commit makes the <basename>_oss_fuzz targets of java_fuzz_test
instances work in OSS-Fuzz, based on the runfiles support and the
handling of OSS-Fuzz provided binaries introduced in previous PRs.
The following parts of the commit are notable:
* The Jazzer update results in a simplified runfiles structure of the
driver, which prevents runfile paths clashes.
* Since .options files are discouraged, target-dependant shell scripts
are used to set the required options for sanitizers.
* The transitive_native_deps attribute of java_fuzz_test is removed in
favor of an overapproximation of the Java library path, which makes
the java_fuzz_test easier to use with Bazel 4.
Replaces #146.
=> Add OSS-Fuzz support to java_fuzz_test

.bazelrc, fuzzing/repositories.bzl
While the `cc_engine_instrumentation` settings `libfuzzer` and `jazzer` lead to the same instrumentation, this may not remain so indefinitely. Thus the `jazzer` and `asan-jazzer` config in `.bazelrc` should use the `jazzer` value for the setting.
Also, even when not using a sanitizer via the `jazzer` config, native library dependencies should be instrumented for fuzzing.
This requires updating Jazzer to the latest version as previous versions did not correctly export certain sanitizer symbols.
=> Use correct `cc_engine_instrumentation` in `jazzer` config

fuzzing/private/common.bzl
While `cc_fuzz_test` and `java_fuzz_test` do find their runfiles when
executed, this is not strictly guaranteed without an explicitly set
`RUNFILES_DIR` variable.
=> Set `RUNFILES_DIR` in launcher

fuzzing/instrum_opts.bzl, fuzzing/private/instrum_opts.bzl
Jazzer is based on libFuzzer and hence generally requires the same
instrumentation for native code. Since it does not support
LeakSanitizer, the corresponding instrumentation can be disabled to
save some (potentially negligible) runtime cost.
=> Disable leak instrumentation for Jazzer

fuzzing/engines/honggfuzz_launcher.sh, fuzzing/engines/jazzer_launcher.sh, fuzzing/engines/libfuzzer_launcher.sh, fuzzing/engines/replay_launcher.sh, fuzzing/tools/launcher.py
Do not add "--" when passing args into the engine launcher since other options are passed using environment variables; In engine launchers, append the args to the fuzzer command.
=> Pass args from lanuchers to the fuzzers.

.github/workflows/bazel_test.yml, BUILD, examples/BUILD, fuzzing/engines/honggfuzz_launcher.sh, fuzzing/engines/jazzer_launcher.sh, fuzzing/engines/libfuzzer_launcher.sh, fuzzing/engines/replay_launcher.sh, fuzzing/private/fuzz_test.bzl, fuzzing/private/java_utils.bzl, fuzzing/replay/replay_main.cc, fuzzing/repositories.bzl
=> Restore and verify GCC compatibility

fuzzing/private/java_utils.bzl
Many Java projects using native libraries add them as resources rather
than relying on Bazel to add them to the native library path. This
change ensure that these libraries are correctly instrumented for
fuzzing.
=> Instrument native libraries in deploy JARs

fuzzing/private/oss_fuzz/repository.bzl
This simplifies the oss_fuzz repository rule.
=> Link UBSan C++ runtime with a flag rather than explicitly

fuzzing/private/fuzz_test.bzl
Some of Jazzer's extra features use manifest entries and this makes it possible to use them with `rules_fuzzing`.
Since I am manipulating a new `kwarg` here I decided to generalize and cherr-pick https://github.com/bazelbuild/rules_fuzzing/pull/181/commits/967af935438e3ab0bde260d9e417607ba60837e2.
=> Allow passing deploy_manifest_lines to java_fuzz_test 

.bazelrc, README.md, docs/guide.md, examples/BUILD, examples/java/BUILD, examples/java/com/example/NativeUbsanFuncPtrFuzzTest.cpp, examples/java/com/example/NativeUbsanFuncPtrFuzzTest.h, examples/java/com/example/NativeUbsanFuncPtrFuzzTest.java, examples/ubsan_function_ptr_fuzz_test.cc, examples/ubsan_int_overflow_fuzz_test.cc, fuzzing/BUILD, fuzzing/instrum_opts.bzl, fuzzing/private/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/private/instrum_opts.bzl
With Jazzer supporting full UBSan as of https://github.com/CodeIntelligenceTesting/jazzer/pull/169 as well as a much simpler way to link the UBSan C++ runtime via the flag used in #186, UBSan can now be supported in local mode without introducing additional complexity.
The list of enabled UBSan checks is taken from OSS-Fuzz.
The commit also adds tests to verify that both C++ and Java fuzz tests support the UBSan C++ checks without linker errors.
=> Support UBSan for local fuzzing

fuzzing/private/java_utils.bzl
See the individual commit messages.
=> Fix native library handling

fuzzing/init.bzl, fuzzing/repositories.bzl
This allows us to get rid of the py_repositories() call in init.bzl.
This call is no longer needed with newer versions of rules_python and produces warnings.
Fixes #198
=> Update rules_python to 0.6.0

.github/workflows/bazel_lint.yml, fuzzing/private/binary.bzl, fuzzing/private/common.bzl
go get is no longer a supported way to install binaries.
=> Fix bazel_lint job

examples/BUILD, examples/java/BUILD, fuzzing/private/fuzz_test.bzl
=> Support "size" and "timeout" on *_fuzz_test

.github/workflows/bazel_test.yml, fuzzing/private/common.bzl
Without `use_default_shell_env`, `PATH` was not set for Python actions, which resulted in `python` (or `python3`) not being found.
=> Use Bazel's default `PATH` when running Python actions

fuzzing/private/instrum_opts.bzl
OSS-Fuzz uses different compile-time settings for UBSan tuned for their setup, but it doesn't make sense to enforce these also for local users.
In OSS-Fuzz mode, these flags will still be picked up from the environment.
=> Do not deviate from UBSan default for local fuzzing

.bazelrc, .github/workflows/bazel_test.yml, BUILD, fuzzing/private/binary.bzl, fuzzing/private/regression.bzl, fuzzing/tools/BUILD, fuzzing/tools/noop_lcov_merger.sh
Co-authored-by: Zhen Yu Ding <zhendeveloper@gmail.com>
Closes #174
=> Add coverage support to C++ regression tests

.bazelrc, README.md, WORKSPACE, fuzzing/engines/BUILD, fuzzing/private/BUILD, fuzzing/private/fuzz_test.bzl, fuzzing/private/java_utils.bzl, fuzzing/private/oss_fuzz/BUILD.tpl, fuzzing/private/oss_fuzz/instrum.bzl.tpl, fuzzing/private/oss_fuzz/package.bzl, fuzzing/private/oss_fuzz/repository.bzl, fuzzing/private/runtime/BUILD, fuzzing/private/runtime/clang_runtime_lib.bzl, fuzzing/repositories.bzl
This commit updates Jazzer to v0.17.1 and restores compatibility with OSS-Fuzz after its recent Jazzer update.
Since Jazzer can now be run directly as a `java_binary` obtained from Maven, the setup required for `java_fuzz_test` has been simplified:
* Jazzer can now be used without extra WORKSPACE setup.
* The Jazzer runtime is represented as an engine analogous to the case of C++ fuzz engines.
* Since Jazzer now loads the correct sanitizer runtimes at runtime, it's no longer necessary to use different Jazzer binaries depending on the sanitizer setting. Logic is added to collect the runtimes from the C++ toolchain at build time and add them to Jazzer's runfiles.
The Jazzer update also makes rules_fuzzing compatible with Bazel 6.
=> Update and simplify Jazzer integration

.bazelrc, docs/guide.md, fuzzing/BUILD, fuzzing/instrum_opts.bzl
This option combines ASan with UBSan, which is very useful for running the replay tests as well as while iterating on a fuzz test locally.
=> Add `asan-ubsan` instrumentation option

fuzzing/private/fuzz_test.bzl
In certain situations, `java_fuzz_test`s failed with
```
ERROR: Projects/fuzz-sample/BUILD:3:15: in java_binary rule //:JavaFuzzTest_metadata_: need at least one of 'main_class' or Java source files
ERROR: Projects/fuzz-sample/BUILD:3:15: in java_binary rule //:JavaFuzzTest_metadata_: main_class was not provided and cannot be inferred: source path doesn't include a known root (java, javatests, src, testsrc)
ERROR: Projects/fuzz-sample/BUILD:3:15: Analysis of target '//:JavaFuzzTest_metadata_' failed
```
This is fixed by marking the metadata jar as non-executable.
Fixes #235
=> Fix `main_class` error in `java_fuzz_test`

.bazelrc, fuzzing/repositories.bzl
NOTE: abseil-cpp started requiring C++14 in the 2023 January LTS release, so if this is merged, users on [old compilers](https://github.com/google/oss-policies-info/blob/b842c39db88e6569dfe2cf98be434b03507cb503/foundational-cxx-support-matrix.md) may have to override abseil-cpp to an older version.
This fixes a build error in newer Clang caused by a
feature=layering_check violation:
```
In file included from external/com_google_absl/absl/debugging/stacktrace.cc:46:
external/com_google_absl/absl/debugging/internal/stacktrace_x86-inl.inc:38:10: error: module @com_google_absl//absl/debugging:stacktrace does not depend on a module exporting 'absl/base/internal/raw_logging.h'
^
1 error generated.
```
This commit in abseil-cpp fixing the error is …
=> Update abseil-cpp to fix build with Clang >=16

WORKSPACE, fuzzing/repositories.bzl, fuzzing/requirements.txt, fuzzing/tools/validate_dict.py
This seems to be necessary for the project to build successfully with Bazel 6.
I also fixed some build errors related to Python 3.12, by upgrading to the most recent versions of absl, six, and rules_python.
=> Fix import to include full path

fuzzing/init.bzl
The `requirements` argument is deprecated and will be removed in the next rules_python release.
Fixes #239
=> Update pip_parse invocation

fuzzing/repositories.bzl
for `WORKSPACE` dependencies. `MODULE.bazel` already uses this version.
=> Update rules_python to 0.28.0

.github/workflows/oss_fuzz.yml, fuzzing/replay/file_util.cc, fuzzing/replay/file_util_test.cc
The replayer would not execute hidden corpus files or files in hidden directories if they were in the bazel project root (#253).
=> fix(replayer): replay corpus files in hidden dirs

.bazelrc, docs/guide.md, fuzzing/engines/BUILD
This allows Bzlmod users to reference the engines without reaching into rules_fuzzing internals.
Work towards #257
=> Add aliases for OSS-Fuzz engines

MODULE.bazel, fuzzing/private/extensions.bzl
This removes an unnecessary entry from the lockfiles of rules_fuzzing users.
=> Mark extension as reproducible

docs/cc-fuzzing-rules.md, docs/java-fuzzing-rules.md, fuzzing/private/fuzz_test.bzl
Forwards `tags` and `target_compatible_with` to the generated targets from `cc_fuzz_test`, `java_fuzz_test` and `fuzzing_decoration`.
Being able to modify tags and specify platform constraints is frequently needed in CI/CD integrations.
=> Propagate tags and target_compatible_with to generated bazel targets

.bcr/source.template.json
The release job creates an archive with the `v`-prefixed tag in the name, which caused the publish job to fail as it expected the name without the `v`.
https://github.com/bazel-contrib/rules_fuzzing/actions/runs/16354558276/job/46210158348#step:6:24
=> Fix source.template.json
